// src/lib/preview/Preview.svelte
<script lang="ts">
  // Read-only markdown preview pane. Renders via the marked pipeline and
  // styles the output to match the editor's typographic scale so a user
  // flipping between raw, split, and preview modes sees the same line lengths
  // and text weights across all three.
  //
  // The rendered HTML is inserted via `{@html}`. We consider file content
  // trusted input (see markdown.ts for the justification). If that ever
  // changes, sanitize in the pipeline, not here.
  //
  // Debouncing note: the body prop updates on every keystroke. Re-running
  // marked on each keystroke produces visible flicker when the user types
  // a character that temporarily breaks an emphasis span (e.g. a trailing
  // space inside `**bold **`, which CommonMark treats as not-bold until the
  // text is typed further). A 150ms debounce coalesces keystroke bursts into
  // a single render, so those transient states never reach the DOM.
  //
  // Link click handling: rendered markdown links are `<a href="...">` in the
  // DOM. A bare click would navigate the webview — SvelteKit treats any
  // same-origin click as a route change and fires a 404 for anything that
  // isn't `/`. We intercept at the container level: relative markdown links
  // route through `project.openTab`; external schemes open in the user's
  // browser via the opener plugin.

  import { onDestroy } from "svelte";
  import { renderMarkdown } from "./markdown";
  import { project } from "$lib/stores/project.svelte";
  import { notify } from "$lib/stores/notifications.svelte";
  import { formatError } from "$lib/errors";
  import { openUrl } from "@tauri-apps/plugin-opener";

  type Props = {
    body: string;
  };

  let { body }: Props = $props();

  function isExternalHref(href: string): boolean {
    return (
      /^[a-z][a-z0-9+.-]*:/i.test(href) ||
      href.startsWith("//") ||
      href.startsWith("#")
    );
  }

  function resolveRelativeHref(
    sourcePath: string,
    href: string,
  ): string | null {
    // Build the source file's parent segments.
    const sourceSegments = sourcePath.split("/").filter(Boolean);
    sourceSegments.pop(); // drop the file name
    const linkSegments = href.split("/").filter(Boolean);
    const combined = [...sourceSegments];
    for (const seg of linkSegments) {
      if (seg === ".") continue;
      if (seg === "..") {
        if (combined.length === 0) return null; // would escape project root
        combined.pop();
        continue;
      }
      combined.push(seg);
    }
    return combined.join("/");
  }

  function handleClick(e: MouseEvent) {
    // Modifier-clicks (open in new window etc.) aren't meaningful in a
    // single-window Tauri app but leave them to the browser anyway.
    if (e.metaKey || e.ctrlKey || e.shiftKey || e.altKey) return;

    const target = e.target as Element | null;
    const anchor = target?.closest?.("a") as HTMLAnchorElement | null;
    if (!anchor) return;

    const href = anchor.getAttribute("href");
    if (!href) return;

    if (isExternalHref(href)) {
      // Open externals (http://, mailto:, etc.) in the system default
      // handler rather than the webview, which can't nav-navigate
      // cross-origin cleanly in SPA mode anyway.
      e.preventDefault();
      void openUrl(href).catch((err) => {
        notify.error(`Couldn't open ${href}: ${formatError(err)}`, err);
      });
      return;
    }

    // Internal relative link — must resolve against the active tab's
    // path or we don't know where we are.
    const sourcePath = project.activeTab?.path;
    if (!sourcePath) return;
    const resolved = resolveRelativeHref(sourcePath, href);
    if (!resolved) return;
    // Only .md / .markdown files are openable in Skrive today. Non-
    // markdown targets (images, pdfs, etc.) fall through — the default
    // navigation would 404 too, but that's a broader follow-up.
    if (!/\.(md|markdown)$/i.test(resolved)) return;

    e.preventDefault();
    void project.openTab(resolved).catch((err) => {
      notify.error(
        `Couldn't open ${resolved}: ${formatError(err)}`,
        err,
      );
    });
  }

  const DEBOUNCE_MS = 150;
  let debouncedBody = $state("");
  let pending: ReturnType<typeof setTimeout> | null = null;
  let mounted = false;

  $effect(() => {
    // Read `body` so the effect re-runs when it changes.
    const next = body;
    if (!mounted) {
      // First pass — take the initial body immediately so the preview
      // renders the opened file with no delay.
      mounted = true;
      debouncedBody = next;
      return;
    }
    if (pending) clearTimeout(pending);
    pending = setTimeout(() => {
      debouncedBody = next;
      pending = null;
    }, DEBOUNCE_MS);
  });

  onDestroy(() => {
    if (pending) clearTimeout(pending);
  });

  let html = $derived(
    renderMarkdown(debouncedBody, {
      projectRoot: project.manifest?.root ?? "",
      filePath: project.activeTab?.path ?? null,
    }),
  );
</script>

<!-- svelte-ignore a11y_click_events_have_key_events -->
<!-- svelte-ignore a11y_no_noninteractive_element_interactions -->
<div class="preview" role="document" onclick={handleClick}>
  <div class="preview-inner">
    {@html html}
  </div>
</div>

<style>
  .preview {
    height: 100%;
    width: 100%;
    overflow-y: auto;
    background: var(--skrive-bg);
    color: var(--skrive-fg);
  }

  .preview-inner {
    max-width: 42rem;
    margin: 0 auto;
    padding: 2.5rem 2rem 6rem;
    /* Track the editor's font choice so split view stays coherent.
       Size + line-height stay as relative defaults — the preview's
       heading scale cascades from `font-size: 1rem` and changing it
       would resize every heading too. The Settings sliders only
       affect the raw editor surface today. */
    font-family: var(--skrive-editor-font);
    font-size: 1rem;
    line-height: 1.65;
  }

  .preview-inner :global(h1),
  .preview-inner :global(h2),
  .preview-inner :global(h3),
  .preview-inner :global(h4),
  .preview-inner :global(h5),
  .preview-inner :global(h6) {
    font-weight: 600;
    letter-spacing: -0.015em;
    line-height: 1.25;
    margin: 1.75em 0 0.5em;
    color: var(--skrive-fg);
  }

  .preview-inner :global(h1) {
    font-size: 1.85rem;
    margin-top: 0;
  }
  .preview-inner :global(h2) {
    font-size: 1.45rem;
  }
  .preview-inner :global(h3) {
    font-size: 1.2rem;
  }
  .preview-inner :global(h4),
  .preview-inner :global(h5),
  .preview-inner :global(h6) {
    font-size: 1.05rem;
  }

  .preview-inner :global(p) {
    margin: 0 0 1em;
  }

  .preview-inner :global(a) {
    color: var(--skrive-link);
    text-decoration: underline;
    text-decoration-thickness: 1px;
    text-underline-offset: 2px;
  }

  .preview-inner :global(strong) {
    font-weight: 600;
  }

  .preview-inner :global(em) {
    font-style: italic;
  }

  .preview-inner :global(ul),
  .preview-inner :global(ol) {
    margin: 0 0 1em;
    padding-left: 1.5em;
  }

  .preview-inner :global(li) {
    margin-bottom: 0.25em;
  }

  .preview-inner :global(blockquote) {
    margin: 1em 0;
    padding: 0.25em 0 0.25em 1em;
    border-left: 2px solid var(--skrive-rule);
    color: var(--skrive-muted);
  }

  .preview-inner :global(hr) {
    border: 0;
    border-top: 1px solid var(--skrive-rule);
    margin: 2em 0;
  }

  .preview-inner :global(code) {
    font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
    font-size: 0.9em;
    background: var(--skrive-rule);
    padding: 0.1em 0.35em;
    border-radius: 3px;
  }

  .preview-inner :global(pre) {
    background: var(--skrive-rule);
    padding: 1em;
    border-radius: 4px;
    overflow-x: auto;
    margin: 1em 0;
    line-height: 1.5;
  }

  .preview-inner :global(pre code) {
    background: transparent;
    padding: 0;
    font-size: 0.85rem;
  }

  .preview-inner :global(img) {
    max-width: 100%;
    height: auto;
  }

  .preview-inner :global(table) {
    border-collapse: collapse;
    width: 100%;
    margin: 1em 0;
    font-size: 0.95em;
  }

  .preview-inner :global(th),
  .preview-inner :global(td) {
    border-bottom: 1px solid var(--skrive-rule);
    padding: 0.5em 0.75em;
    text-align: left;
  }

  .preview-inner :global(th) {
    font-weight: 600;
  }
</style>

// app/src/components/editor/Preview.tsx
// Read-only markdown preview pane. Renders via the marked pipeline and
// styles the output to match the editor's typographic scale so a user
// flipping between raw, split, and preview modes sees the same line
// lengths and text weights across all three.
//
// The rendered HTML is inserted via `dangerouslySetInnerHTML`. We
// consider file content trusted input (see markdown.ts for the
// justification). If that ever changes, sanitize in the pipeline, not
// here.
//
// Debouncing: the body prop updates on every keystroke. Re-running marked
// on each keystroke produces visible flicker when the user types a
// character that temporarily breaks an emphasis span. A 150ms debounce
// coalesces keystroke bursts into a single render.
//
// Link click handling: external schemes go through the OS via the
// `links:openExternal` IPC. Internal relative links are routed via the
// `onInternalLink` callback (Phase 6 wires this through to the project
// store; Phase 2 ignores them).

import { useEffect, useMemo, useRef, useState } from 'react';
import { renderMarkdown, stripLeadingFrontmatter } from '../../lib/preview/markdown';
import { skriveAssetResolver } from '../../lib/preview/imageResolver';
import { buildClipboardPayload } from '../../lib/clipboard/copyOut';
import { IconCopy } from '../icons/IconCopy';
import { IconCheck } from '../icons/IconCheck';
import { PreviewOutlineRail } from './PreviewOutlineRail';

const COPIED_FEEDBACK_MS = 1600;

type Props = {
  body: string;
  /**
   * Active document's project-relative path, used to resolve relative image
   * URLs against the project (via the skrive-asset protocol).
   */
  filePath?: string | null;
  /** Project root, forwarded into the image resolver's context. */
  projectRoot?: string;
  /**
   * Called when the user clicks an internal (relative) link in the
   * rendered HTML. Phase 6 wires this through to the project store;
   * Phase 2 leaves it as a no-op default.
   */
  onInternalLink?: (href: string) => void;
  /**
   * Show the outline rail down the right edge. Only enabled in
   * preview-only layout (the rail navigates the rendered document, not
   * the editor); the caller gates this on layout mode + preference.
   */
  showRail?: boolean;
};

const DEBOUNCE_MS = 150;

// `#fragment` links are handled separately (scroll within the preview),
// so they are intentionally *not* treated as external here — the caller
// checks for them first.
function isExternalHref(href: string): boolean {
  return /^[a-z][a-z0-9+.-]*:/i.test(href) || href.startsWith('//');
}

export function Preview({
  body,
  filePath = null,
  projectRoot = '',
  onInternalLink,
  showRail = false
}: Props) {
  const [debouncedBody, setDebouncedBody] = useState(body);
  const mountedRef = useRef(false);
  const timerRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  useEffect(() => {
    if (!mountedRef.current) {
      mountedRef.current = true;
      setDebouncedBody(body);
      return;
    }
    if (timerRef.current) clearTimeout(timerRef.current);
    timerRef.current = setTimeout(() => {
      setDebouncedBody(body);
      timerRef.current = null;
    }, DEBOUNCE_MS);
  }, [body]);

  useEffect(() => {
    return () => {
      if (timerRef.current) clearTimeout(timerRef.current);
    };
  }, []);

  const html = useMemo(
    () =>
      renderMarkdown(debouncedBody, {
        context: { projectRoot, filePath },
        resolver: skriveAssetResolver
      }),
    [debouncedBody, projectRoot, filePath]
  );
  const scrollerRef = useRef<HTMLDivElement | null>(null);
  const innerRef = useRef<HTMLDivElement | null>(null);

  // Copy-out for preview mode. The editor's copy handler doesn't cover this
  // surface, and the browser's native copy of the rendered DOM drags the
  // theme background into rich targets. This button copies the whole document
  // as a clean dual-write payload built from the renderer, not the DOM, so
  // there's no styling to bleed. Frontmatter is stripped to match what the
  // preview shows.
  const [copied, setCopied] = useState(false);
  const copyTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const documentBody = stripLeadingFrontmatter(body).trim();

  useEffect(() => {
    return () => {
      if (copyTimerRef.current) clearTimeout(copyTimerRef.current);
    };
  }, []);

  async function copyDocument() {
    const { text, html: rendered } = buildClipboardPayload(documentBody);
    try {
      await navigator.clipboard.write([
        new ClipboardItem({
          'text/plain': new Blob([text], { type: 'text/plain' }),
          'text/html': new Blob([rendered], { type: 'text/html' })
        })
      ]);
    } catch {
      // Some environments refuse rich clipboard writes; fall back to plain.
      try {
        await navigator.clipboard.writeText(text);
      } catch (err) {
        console.warn('[skrive] copy to clipboard failed:', err);
        return;
      }
    }
    setCopied(true);
    if (copyTimerRef.current) clearTimeout(copyTimerRef.current);
    copyTimerRef.current = setTimeout(() => setCopied(false), COPIED_FEEDBACK_MS);
  }

  // Scroll the preview to a same-document heading. An empty fragment
  // ("#") is the conventional "back to top". Fragments may be percent-
  // encoded by the renderer for non-ASCII slugs, so decode before
  // matching the `id` we assigned in markdown.ts.
  function scrollToFragment(rawFragment: string) {
    const scroller = scrollerRef.current;
    if (!scroller) return;
    if (rawFragment === '') {
      scroller.scrollTo({ top: 0, behavior: 'smooth' });
      return;
    }
    let id = rawFragment;
    try {
      id = decodeURIComponent(rawFragment);
    } catch {
      // Malformed escape — fall back to the raw fragment.
    }
    const target = scroller.querySelector(`#${CSS.escape(id)}`);
    if (target instanceof HTMLElement) {
      target.scrollIntoView({ behavior: 'smooth', block: 'start' });
    }
  }

  function handleClick(e: React.MouseEvent<HTMLDivElement>) {
    // Modifier-clicks (open in new window etc.) aren't meaningful in a
    // single-window app but leave them to the browser anyway.
    if (e.metaKey || e.ctrlKey || e.shiftKey || e.altKey) return;

    const target = e.target as Element | null;
    const anchor = target?.closest?.('a') as HTMLAnchorElement | null;
    if (!anchor) return;

    const href = anchor.getAttribute('href');
    if (!href) return;

    // Same-document anchor: scroll the preview, never leave the app.
    if (href.startsWith('#')) {
      e.preventDefault();
      scrollToFragment(href.slice(1));
      return;
    }

    if (isExternalHref(href)) {
      e.preventDefault();
      void window.skrive.links.openExternal(href).catch((err) => {
        console.warn(`[skrive] couldn't open ${href}:`, err);
      });
      return;
    }

    // Internal relative link — Phase 6 wires this through to the
    // project store. Phase 2 calls the callback if provided, else
    // does nothing (no project store exists yet).
    if (onInternalLink) {
      e.preventDefault();
      onInternalLink(href);
    }
  }

  return (
    <div className={`preview-host${showRail ? ' has-rail' : ''}`}>
      <div
        className="preview"
        role="document"
        onClick={handleClick}
        ref={scrollerRef}
      >
        <div
          className="preview-inner"
          ref={innerRef}
          dangerouslySetInnerHTML={{ __html: html }}
        />
      </div>
      {documentBody !== '' && (
        <button
          type="button"
          className={`preview-copy${copied ? ' copied' : ''}`}
          title={copied ? 'Copied' : 'Copy document'}
          aria-label={
            copied ? 'Document copied to clipboard' : 'Copy document to clipboard'
          }
          onClick={copyDocument}
        >
          {/* Both glyphs are stacked and crossfaded in CSS; a brief blur
              bridges the copy -> check swap so it reads as one continuous
              state change rather than a hard cut. */}
          <span className="preview-copy-glyphs">
            <IconCopy size={16} className="preview-copy-glyph is-copy" />
            <IconCheck size={16} className="preview-copy-glyph is-check" />
          </span>
        </button>
      )}
      {showRail && (
        <PreviewOutlineRail
          scrollerRef={scrollerRef}
          contentRef={innerRef}
          renderKey={html}
        />
      )}
    </div>
  );
}
